### ISSUE TITLE
Stray `n` in src/components/styles.js

### ISSUE THREAD

**Issue by pdehaan** [mozilla-extensions/mozilla-vpn-extension#88]
Was randomly browsing your CSS (as one does) and noticed this little guy hangin' out.

https://github.com/mozilla-extensions/mozilla-vpn-extension/blob/5d3c8f5b8307050f25b855a1d2cf1e2e0857bb67/src/components/styles.js#L13

**Comment by lesleyjanenorton** [comment]
Git blame says I'm guilty
